%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'tax_dsge_est';
M_.dynare_version = '5.5';
oo_.dynare_version = '5.5';
options_.dynare_version = '5.5';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(14,1);
M_.exo_names_tex = cell(14,1);
M_.exo_names_long = cell(14,1);
M_.exo_names(1) = {'eps_g'};
M_.exo_names_tex(1) = {'eps\_g'};
M_.exo_names_long(1) = {'eps_g'};
M_.exo_names(2) = {'eps_tr'};
M_.exo_names_tex(2) = {'eps\_tr'};
M_.exo_names_long(2) = {'eps_tr'};
M_.exo_names(3) = {'eps_k'};
M_.exo_names_tex(3) = {'eps\_k'};
M_.exo_names_long(3) = {'eps_k'};
M_.exo_names(4) = {'eps_w'};
M_.exo_names_tex(4) = {'eps\_w'};
M_.exo_names_long(4) = {'eps_w'};
M_.exo_names(5) = {'eps_z'};
M_.exo_names_tex(5) = {'eps\_z'};
M_.exo_names_long(5) = {'eps_z'};
M_.exo_names(6) = {'eps_d'};
M_.exo_names_tex(6) = {'eps\_d'};
M_.exo_names_long(6) = {'eps_d'};
M_.exo_names(7) = {'eps_mu'};
M_.exo_names_tex(7) = {'eps\_mu'};
M_.exo_names_long(7) = {'eps_mu'};
M_.exo_names(8) = {'eps_m'};
M_.exo_names_tex(8) = {'eps\_m'};
M_.exo_names_long(8) = {'eps_m'};
M_.exo_names(9) = {'eps_c'};
M_.exo_names_tex(9) = {'eps\_c'};
M_.exo_names_long(9) = {'eps_c'};
M_.exo_names(10) = {'eps_ic'};
M_.exo_names_tex(10) = {'eps\_ic'};
M_.exo_names_long(10) = {'eps_ic'};
M_.exo_names(11) = {'eps_ti'};
M_.exo_names_tex(11) = {'eps\_ti'};
M_.exo_names_long(11) = {'eps_ti'};
M_.exo_names(12) = {'eps_td'};
M_.exo_names_tex(12) = {'eps\_td'};
M_.exo_names_long(12) = {'eps_td'};
M_.exo_names(13) = {'eps_etau'};
M_.exo_names_tex(13) = {'eps\_etau'};
M_.exo_names_long(13) = {'eps_etau'};
M_.exo_names(14) = {'eps_b'};
M_.exo_names_tex(14) = {'eps\_b'};
M_.exo_names_long(14) = {'eps_b'};
M_.endo_names = cell(60,1);
M_.endo_names_tex = cell(60,1);
M_.endo_names_long = cell(60,1);
M_.endo_names(1) = {'c'};
M_.endo_names_tex(1) = {'c'};
M_.endo_names_long(1) = {'c'};
M_.endo_names(2) = {'g'};
M_.endo_names_tex(2) = {'g'};
M_.endo_names_long(2) = {'g'};
M_.endo_names(3) = {'i'};
M_.endo_names_tex(3) = {'i'};
M_.endo_names_long(3) = {'i'};
M_.endo_names(4) = {'k'};
M_.endo_names_tex(4) = {'k'};
M_.endo_names_long(4) = {'k'};
M_.endo_names(5) = {'u'};
M_.endo_names_tex(5) = {'u'};
M_.endo_names_long(5) = {'u'};
M_.endo_names(6) = {'h'};
M_.endo_names_tex(6) = {'h'};
M_.endo_names_long(6) = {'h'};
M_.endo_names(7) = {'y'};
M_.endo_names_tex(7) = {'y'};
M_.endo_names_long(7) = {'y'};
M_.endo_names(8) = {'xc'};
M_.endo_names_tex(8) = {'xc'};
M_.endo_names_long(8) = {'xc'};
M_.endo_names(9) = {'xg'};
M_.endo_names_tex(9) = {'xg'};
M_.endo_names_long(9) = {'xg'};
M_.endo_names(10) = {'sC'};
M_.endo_names_tex(10) = {'sC'};
M_.endo_names_long(10) = {'sC'};
M_.endo_names(11) = {'sG'};
M_.endo_names_tex(11) = {'sG'};
M_.endo_names_long(11) = {'sG'};
M_.endo_names(12) = {'lambda'};
M_.endo_names_tex(12) = {'lambda'};
M_.endo_names_long(12) = {'lambda'};
M_.endo_names(13) = {'q'};
M_.endo_names_tex(13) = {'q'};
M_.endo_names_long(13) = {'q'};
M_.endo_names(14) = {'rk'};
M_.endo_names_tex(14) = {'rk'};
M_.endo_names_long(14) = {'rk'};
M_.endo_names(15) = {'w'};
M_.endo_names_tex(15) = {'w'};
M_.endo_names_long(15) = {'w'};
M_.endo_names(16) = {'mc'};
M_.endo_names_tex(16) = {'mc'};
M_.endo_names_long(16) = {'mc'};
M_.endo_names(17) = {'pi'};
M_.endo_names_tex(17) = {'pi'};
M_.endo_names_long(17) = {'pi'};
M_.endo_names(18) = {'piw'};
M_.endo_names_tex(18) = {'piw'};
M_.endo_names_long(18) = {'piw'};
M_.endo_names(19) = {'R'};
M_.endo_names_tex(19) = {'R'};
M_.endo_names_long(19) = {'R'};
M_.endo_names(20) = {'b'};
M_.endo_names_tex(20) = {'b'};
M_.endo_names_long(20) = {'b'};
M_.endo_names(21) = {'tr'};
M_.endo_names_tex(21) = {'tr'};
M_.endo_names_long(21) = {'tr'};
M_.endo_names(22) = {'taxrev'};
M_.endo_names_tex(22) = {'taxrev'};
M_.endo_names_long(22) = {'taxrev'};
M_.endo_names(23) = {'tau_k'};
M_.endo_names_tex(23) = {'tau\_k'};
M_.endo_names_long(23) = {'tau_k'};
M_.endo_names(24) = {'tau_w'};
M_.endo_names_tex(24) = {'tau\_w'};
M_.endo_names_long(24) = {'tau_w'};
M_.endo_names(25) = {'tau_c'};
M_.endo_names_tex(25) = {'tau\_c'};
M_.endo_names_long(25) = {'tau_c'};
M_.endo_names(26) = {'tau_ic'};
M_.endo_names_tex(26) = {'tau\_ic'};
M_.endo_names_long(26) = {'tau_ic'};
M_.endo_names(27) = {'tau_i'};
M_.endo_names_tex(27) = {'tau\_i'};
M_.endo_names_long(27) = {'tau_i'};
M_.endo_names(28) = {'tau_d'};
M_.endo_names_tex(28) = {'tau\_d'};
M_.endo_names_long(28) = {'tau_d'};
M_.endo_names(29) = {'k_tau'};
M_.endo_names_tex(29) = {'k\_tau'};
M_.endo_names_long(29) = {'k_tau'};
M_.endo_names(30) = {'v_tau'};
M_.endo_names_tex(30) = {'v\_tau'};
M_.endo_names_long(30) = {'v_tau'};
M_.endo_names(31) = {'div'};
M_.endo_names_tex(31) = {'div'};
M_.endo_names_long(31) = {'div'};
M_.endo_names(32) = {'e_tau'};
M_.endo_names_tex(32) = {'e\_tau'};
M_.endo_names_long(32) = {'e_tau'};
M_.endo_names(33) = {'nu_c'};
M_.endo_names_tex(33) = {'nu\_c'};
M_.endo_names_long(33) = {'nu_c'};
M_.endo_names(34) = {'nu_g'};
M_.endo_names_tex(34) = {'nu\_g'};
M_.endo_names_long(34) = {'nu_g'};
M_.endo_names(35) = {'nu_i'};
M_.endo_names_tex(35) = {'nu\_i'};
M_.endo_names_long(35) = {'nu_i'};
M_.endo_names(36) = {'z'};
M_.endo_names_tex(36) = {'z'};
M_.endo_names_long(36) = {'z'};
M_.endo_names(37) = {'d'};
M_.endo_names_tex(37) = {'d'};
M_.endo_names_long(37) = {'d'};
M_.endo_names(38) = {'mu'};
M_.endo_names_tex(38) = {'mu'};
M_.endo_names_long(38) = {'mu'};
M_.endo_names(39) = {'wtilde'};
M_.endo_names_tex(39) = {'wtilde'};
M_.endo_names_long(39) = {'wtilde'};
M_.endo_names(40) = {'rev_c'};
M_.endo_names_tex(40) = {'rev\_c'};
M_.endo_names_long(40) = {'rev_c'};
M_.endo_names(41) = {'rev_w'};
M_.endo_names_tex(41) = {'rev\_w'};
M_.endo_names_long(41) = {'rev_w'};
M_.endo_names(42) = {'rev_k'};
M_.endo_names_tex(42) = {'rev\_k'};
M_.endo_names_long(42) = {'rev_k'};
M_.endo_names(43) = {'rev_i'};
M_.endo_names_tex(43) = {'rev\_i'};
M_.endo_names_long(43) = {'rev_i'};
M_.endo_names(44) = {'rev_d'};
M_.endo_names_tex(44) = {'rev\_d'};
M_.endo_names_long(44) = {'rev_d'};
M_.endo_names(45) = {'spend_ic'};
M_.endo_names_tex(45) = {'spend\_ic'};
M_.endo_names_long(45) = {'spend_ic'};
M_.endo_names(46) = {'rev_net'};
M_.endo_names_tex(46) = {'rev\_net'};
M_.endo_names_long(46) = {'rev_net'};
M_.endo_names(47) = {'chat'};
M_.endo_names_tex(47) = {'chat'};
M_.endo_names_long(47) = {'chat'};
M_.endo_names(48) = {'ihat'};
M_.endo_names_tex(48) = {'ihat'};
M_.endo_names_long(48) = {'ihat'};
M_.endo_names(49) = {'ghat'};
M_.endo_names_tex(49) = {'ghat'};
M_.endo_names_long(49) = {'ghat'};
M_.endo_names(50) = {'pi_obs'};
M_.endo_names_tex(50) = {'pi\_obs'};
M_.endo_names_long(50) = {'pi_obs'};
M_.endo_names(51) = {'r_obs'};
M_.endo_names_tex(51) = {'r\_obs'};
M_.endo_names_long(51) = {'r_obs'};
M_.endo_names(52) = {'tau_k_hat'};
M_.endo_names_tex(52) = {'tau\_k\_hat'};
M_.endo_names_long(52) = {'tau_k_hat'};
M_.endo_names(53) = {'tau_l_hat'};
M_.endo_names_tex(53) = {'tau\_l\_hat'};
M_.endo_names_long(53) = {'tau_l_hat'};
M_.endo_names(54) = {'bhat'};
M_.endo_names_tex(54) = {'bhat'};
M_.endo_names_long(54) = {'bhat'};
M_.endo_names(55) = {'trhat'};
M_.endo_names_tex(55) = {'trhat'};
M_.endo_names_long(55) = {'trhat'};
M_.endo_names(56) = {'tau_c_hat'};
M_.endo_names_tex(56) = {'tau\_c\_hat'};
M_.endo_names_long(56) = {'tau_c_hat'};
M_.endo_names(57) = {'tau_d_hat'};
M_.endo_names_tex(57) = {'tau\_d\_hat'};
M_.endo_names_long(57) = {'tau_d_hat'};
M_.endo_names(58) = {'tau_itc_hat'};
M_.endo_names_tex(58) = {'tau\_itc\_hat'};
M_.endo_names_long(58) = {'tau_itc_hat'};
M_.endo_names(59) = {'e_tau_hat'};
M_.endo_names_tex(59) = {'e\_tau\_hat'};
M_.endo_names_long(59) = {'e_tau_hat'};
M_.endo_names(60) = {'tau_i_hat'};
M_.endo_names_tex(60) = {'tau\_i\_hat'};
M_.endo_names_long(60) = {'tau_i_hat'};
M_.endo_partitions = struct();
M_.param_names = cell(61,1);
M_.param_names_tex = cell(61,1);
M_.param_names_long = cell(61,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'delta'};
M_.param_names_tex(2) = {'delta'};
M_.param_names_long(2) = {'delta'};
M_.param_names(3) = {'theta'};
M_.param_names_tex(3) = {'theta'};
M_.param_names_long(3) = {'theta'};
M_.param_names(4) = {'eta'};
M_.param_names_tex(4) = {'eta'};
M_.param_names_long(4) = {'eta'};
M_.param_names(5) = {'etaw'};
M_.param_names_tex(5) = {'etaw'};
M_.param_names_long(5) = {'etaw'};
M_.param_names(6) = {'gamma'};
M_.param_names_tex(6) = {'gamma'};
M_.param_names_long(6) = {'gamma'};
M_.param_names(7) = {'kappa'};
M_.param_names_tex(7) = {'kappa'};
M_.param_names_long(7) = {'kappa'};
M_.param_names(8) = {'sig_u'};
M_.param_names_tex(8) = {'sig\_u'};
M_.param_names_long(8) = {'sig_u'};
M_.param_names(9) = {'alphaP'};
M_.param_names_tex(9) = {'alphaP'};
M_.param_names_long(9) = {'alphaP'};
M_.param_names(10) = {'alphaW'};
M_.param_names_tex(10) = {'alphaW'};
M_.param_names_long(10) = {'alphaW'};
M_.param_names(11) = {'bc'};
M_.param_names_tex(11) = {'bc'};
M_.param_names_long(11) = {'bc'};
M_.param_names(12) = {'thetac'};
M_.param_names_tex(12) = {'thetac'};
M_.param_names_long(12) = {'thetac'};
M_.param_names(13) = {'bg'};
M_.param_names_tex(13) = {'bg'};
M_.param_names_long(13) = {'bg'};
M_.param_names(14) = {'thetag'};
M_.param_names_tex(14) = {'thetag'};
M_.param_names_long(14) = {'thetag'};
M_.param_names(15) = {'tauk_ss'};
M_.param_names_tex(15) = {'tauk\_ss'};
M_.param_names_long(15) = {'tauk_ss'};
M_.param_names(16) = {'tauw_ss'};
M_.param_names_tex(16) = {'tauw\_ss'};
M_.param_names_long(16) = {'tauw_ss'};
M_.param_names(17) = {'pi_ss'};
M_.param_names_tex(17) = {'pi\_ss'};
M_.param_names_long(17) = {'pi_ss'};
M_.param_names(18) = {'h_ss'};
M_.param_names_tex(18) = {'h\_ss'};
M_.param_names_long(18) = {'h_ss'};
M_.param_names(19) = {'g_y'};
M_.param_names_tex(19) = {'g\_y'};
M_.param_names_long(19) = {'g_y'};
M_.param_names(20) = {'b_y'};
M_.param_names_tex(20) = {'b\_y'};
M_.param_names_long(20) = {'b_y'};
M_.param_names(21) = {'alphaR'};
M_.param_names_tex(21) = {'alphaR'};
M_.param_names_long(21) = {'alphaR'};
M_.param_names(22) = {'alphapi'};
M_.param_names_tex(22) = {'alphapi'};
M_.param_names_long(22) = {'alphapi'};
M_.param_names(23) = {'alphaY'};
M_.param_names_tex(23) = {'alphaY'};
M_.param_names_long(23) = {'alphaY'};
M_.param_names(24) = {'rho_z'};
M_.param_names_tex(24) = {'rho\_z'};
M_.param_names_long(24) = {'rho_z'};
M_.param_names(25) = {'rho_d'};
M_.param_names_tex(25) = {'rho\_d'};
M_.param_names_long(25) = {'rho_d'};
M_.param_names(26) = {'rho_mu'};
M_.param_names_tex(26) = {'rho\_mu'};
M_.param_names_long(26) = {'rho_mu'};
M_.param_names(27) = {'rho_g'};
M_.param_names_tex(27) = {'rho\_g'};
M_.param_names_long(27) = {'rho_g'};
M_.param_names(28) = {'rho_g_b'};
M_.param_names_tex(28) = {'rho\_g\_b'};
M_.param_names_long(28) = {'rho_g_b'};
M_.param_names(29) = {'rho_g_y'};
M_.param_names_tex(29) = {'rho\_g\_y'};
M_.param_names_long(29) = {'rho_g_y'};
M_.param_names(30) = {'rho_tr'};
M_.param_names_tex(30) = {'rho\_tr'};
M_.param_names_long(30) = {'rho_tr'};
M_.param_names(31) = {'rho_tr_b'};
M_.param_names_tex(31) = {'rho\_tr\_b'};
M_.param_names_long(31) = {'rho_tr_b'};
M_.param_names(32) = {'rho_tr_y'};
M_.param_names_tex(32) = {'rho\_tr\_y'};
M_.param_names_long(32) = {'rho_tr_y'};
M_.param_names(33) = {'rho_k'};
M_.param_names_tex(33) = {'rho\_k'};
M_.param_names_long(33) = {'rho_k'};
M_.param_names(34) = {'rho_k_b'};
M_.param_names_tex(34) = {'rho\_k\_b'};
M_.param_names_long(34) = {'rho_k_b'};
M_.param_names(35) = {'rho_k_y'};
M_.param_names_tex(35) = {'rho\_k\_y'};
M_.param_names_long(35) = {'rho_k_y'};
M_.param_names(36) = {'rho_w'};
M_.param_names_tex(36) = {'rho\_w'};
M_.param_names_long(36) = {'rho_w'};
M_.param_names(37) = {'rho_w_b'};
M_.param_names_tex(37) = {'rho\_w\_b'};
M_.param_names_long(37) = {'rho_w_b'};
M_.param_names(38) = {'rho_w_y'};
M_.param_names_tex(38) = {'rho\_w\_y'};
M_.param_names_long(38) = {'rho_w_y'};
M_.param_names(39) = {'phi'};
M_.param_names_tex(39) = {'phi'};
M_.param_names_long(39) = {'phi'};
M_.param_names(40) = {'tauc_ss'};
M_.param_names_tex(40) = {'tauc\_ss'};
M_.param_names_long(40) = {'tauc_ss'};
M_.param_names(41) = {'rho_c'};
M_.param_names_tex(41) = {'rho\_c'};
M_.param_names_long(41) = {'rho_c'};
M_.param_names(42) = {'rho_c_b'};
M_.param_names_tex(42) = {'rho\_c\_b'};
M_.param_names_long(42) = {'rho_c_b'};
M_.param_names(43) = {'rho_c_y'};
M_.param_names_tex(43) = {'rho\_c\_y'};
M_.param_names_long(43) = {'rho_c_y'};
M_.param_names(44) = {'tauic_ss'};
M_.param_names_tex(44) = {'tauic\_ss'};
M_.param_names_long(44) = {'tauic_ss'};
M_.param_names(45) = {'rho_ic'};
M_.param_names_tex(45) = {'rho\_ic'};
M_.param_names_long(45) = {'rho_ic'};
M_.param_names(46) = {'rho_ic_b'};
M_.param_names_tex(46) = {'rho\_ic\_b'};
M_.param_names_long(46) = {'rho_ic_b'};
M_.param_names(47) = {'rho_ic_y'};
M_.param_names_tex(47) = {'rho\_ic\_y'};
M_.param_names_long(47) = {'rho_ic_y'};
M_.param_names(48) = {'taui_ss'};
M_.param_names_tex(48) = {'taui\_ss'};
M_.param_names_long(48) = {'taui_ss'};
M_.param_names(49) = {'rho_ti'};
M_.param_names_tex(49) = {'rho\_ti'};
M_.param_names_long(49) = {'rho_ti'};
M_.param_names(50) = {'rho_ti_b'};
M_.param_names_tex(50) = {'rho\_ti\_b'};
M_.param_names_long(50) = {'rho_ti_b'};
M_.param_names(51) = {'rho_ti_y'};
M_.param_names_tex(51) = {'rho\_ti\_y'};
M_.param_names_long(51) = {'rho_ti_y'};
M_.param_names(52) = {'taud_ss'};
M_.param_names_tex(52) = {'taud\_ss'};
M_.param_names_long(52) = {'taud_ss'};
M_.param_names(53) = {'rho_td'};
M_.param_names_tex(53) = {'rho\_td'};
M_.param_names_long(53) = {'rho_td'};
M_.param_names(54) = {'rho_td_b'};
M_.param_names_tex(54) = {'rho\_td\_b'};
M_.param_names_long(54) = {'rho_td_b'};
M_.param_names(55) = {'rho_td_y'};
M_.param_names_tex(55) = {'rho\_td\_y'};
M_.param_names_long(55) = {'rho_td_y'};
M_.param_names(56) = {'etau_ss'};
M_.param_names_tex(56) = {'etau\_ss'};
M_.param_names_long(56) = {'etau_ss'};
M_.param_names(57) = {'rho_etau'};
M_.param_names_tex(57) = {'rho\_etau'};
M_.param_names_long(57) = {'rho_etau'};
M_.param_names(58) = {'rho_etau_b'};
M_.param_names_tex(58) = {'rho\_etau\_b'};
M_.param_names_long(58) = {'rho_etau_b'};
M_.param_names(59) = {'rho_etau_y'};
M_.param_names_tex(59) = {'rho\_etau\_y'};
M_.param_names_long(59) = {'rho_etau_y'};
M_.param_names(60) = {'delta_tau'};
M_.param_names_tex(60) = {'delta\_tau'};
M_.param_names_long(60) = {'delta_tau'};
M_.param_names(61) = {'divshare'};
M_.param_names_tex(61) = {'divshare'};
M_.param_names_long(61) = {'divshare'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 14;
M_.endo_nbr = 60;
M_.param_nbr = 61;
M_.orig_endo_nbr = 60;
M_.aux_vars = [];
options_.varobs = cell(12, 1);
options_.varobs(1)  = {'chat'};
options_.varobs(2)  = {'ihat'};
options_.varobs(3)  = {'ghat'};
options_.varobs(4)  = {'bhat'};
options_.varobs(5)  = {'pi_obs'};
options_.varobs(6)  = {'r_obs'};
options_.varobs(7)  = {'tau_k_hat'};
options_.varobs(8)  = {'tau_l_hat'};
options_.varobs(9)  = {'tau_c_hat'};
options_.varobs(10)  = {'tau_itc_hat'};
options_.varobs(11)  = {'e_tau_hat'};
options_.varobs(12)  = {'tau_d_hat'};
options_.varobs_id = [ 47 48 49 54 50 51 52 53 56 58 59 57  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(14, 14);
M_.Correlation_matrix = eye(14, 14);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 60;
M_.eq_nbr = 60;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 22 0;
 1 23 0;
 2 24 82;
 3 25 0;
 0 26 83;
 0 27 0;
 4 28 0;
 0 29 0;
 0 30 0;
 5 31 0;
 6 32 0;
 0 33 84;
 0 34 85;
 0 35 86;
 7 36 0;
 0 37 87;
 0 38 88;
 0 39 89;
 8 40 0;
 9 41 0;
 10 42 0;
 0 43 0;
 11 44 90;
 12 45 0;
 13 46 0;
 14 47 0;
 15 48 91;
 16 49 0;
 17 50 0;
 0 51 92;
 0 52 0;
 18 53 0;
 0 54 93;
 0 55 94;
 0 56 0;
 19 57 0;
 20 58 0;
 21 59 95;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;]';
M_.nstatic = 29;
M_.nfwrd   = 10;
M_.npred   = 17;
M_.nboth   = 4;
M_.nsfwrd   = 14;
M_.nspred   = 21;
M_.ndynamic   = 31;
M_.dynamic_tmp_nbr = [62; 38; 12; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'xc' ;
  2 , 'name' , 'xg' ;
  3 , 'name' , 'sC' ;
  4 , 'name' , 'sG' ;
  5 , 'name' , 'lambda' ;
  6 , 'name' , '6' ;
  7 , 'name' , 'y' ;
  8 , 'name' , 'w' ;
  9 , 'name' , 'rk' ;
  10 , 'name' , '10' ;
  11 , 'name' , 'k' ;
  12 , 'name' , 'k_tau' ;
  13 , 'name' , '13' ;
  14 , 'name' , '14' ;
  15 , 'name' , '15' ;
  16 , 'name' , '16' ;
  17 , 'name' , '17' ;
  18 , 'name' , 'piw' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , '21' ;
  22 , 'name' , '22' ;
  23 , 'name' , '23' ;
  24 , 'name' , 'div' ;
  25 , 'name' , 'b' ;
  26 , 'name' , 'taxrev' ;
  27 , 'name' , '27' ;
  28 , 'name' , '28' ;
  29 , 'name' , '29' ;
  30 , 'name' , '30' ;
  31 , 'name' , '31' ;
  32 , 'name' , '32' ;
  33 , 'name' , '33' ;
  34 , 'name' , '34' ;
  35 , 'name' , '35' ;
  36 , 'name' , '36' ;
  37 , 'name' , '37' ;
  38 , 'name' , '38' ;
  39 , 'name' , '39' ;
  40 , 'name' , 'rev_c' ;
  41 , 'name' , 'rev_w' ;
  42 , 'name' , 'rev_k' ;
  43 , 'name' , 'rev_i' ;
  44 , 'name' , 'rev_d' ;
  45 , 'name' , 'spend_ic' ;
  46 , 'name' , 'rev_net' ;
  47 , 'name' , 'chat' ;
  48 , 'name' , 'ihat' ;
  49 , 'name' , 'ghat' ;
  50 , 'name' , 'pi_obs' ;
  51 , 'name' , 'r_obs' ;
  52 , 'name' , 'tau_k_hat' ;
  53 , 'name' , 'tau_l_hat' ;
  54 , 'name' , 'bhat' ;
  55 , 'name' , 'trhat' ;
  56 , 'name' , 'tau_c_hat' ;
  57 , 'name' , 'tau_d_hat' ;
  58 , 'name' , 'tau_i_hat' ;
  59 , 'name' , 'tau_itc_hat' ;
  60 , 'name' , 'e_tau_hat' ;
};
M_.mapping.c.eqidx = [1 3 10 23 26 40 47 ];
M_.mapping.g.eqidx = [2 4 10 23 25 29 49 ];
M_.mapping.i.eqidx = [10 11 12 16 26 42 45 48 ];
M_.mapping.k.eqidx = [7 8 9 10 11 24 26 42 ];
M_.mapping.u.eqidx = [7 8 9 10 14 15 24 26 42 ];
M_.mapping.h.eqidx = [5 6 7 8 9 10 19 24 26 41 ];
M_.mapping.y.eqidx = [7 23 24 27 28 29 30 31 32 33 34 35 36 ];
M_.mapping.xc.eqidx = [1 5 6 23 ];
M_.mapping.xg.eqidx = [2 23 ];
M_.mapping.sC.eqidx = [1 3 ];
M_.mapping.sG.eqidx = [2 4 ];
M_.mapping.lambda.eqidx = [5 6 13 15 16 17 19 21 22 23 ];
M_.mapping.q.eqidx = [15 16 ];
M_.mapping.rk.eqidx = [9 14 15 24 26 42 ];
M_.mapping.w.eqidx = [6 8 10 18 24 26 41 ];
M_.mapping.mc.eqidx = [8 9 20 21 22 ];
M_.mapping.pi.eqidx = [7 10 17 18 23 25 26 31 43 50 ];
M_.mapping.piw.eqidx = [10 18 19 ];
M_.mapping.R.eqidx = [17 25 26 31 43 51 ];
M_.mapping.b.eqidx = [25 26 27 28 29 30 32 33 34 35 36 43 54 ];
M_.mapping.tr.eqidx = [25 30 55 ];
M_.mapping.taxrev.eqidx = [25 26 ];
M_.mapping.tau_k.eqidx = [13 14 15 16 26 27 42 52 ];
M_.mapping.tau_w.eqidx = [19 26 28 41 53 ];
M_.mapping.tau_c.eqidx = [5 26 32 40 56 ];
M_.mapping.tau_ic.eqidx = [16 26 33 45 59 ];
M_.mapping.tau_i.eqidx = [17 26 34 43 58 ];
M_.mapping.tau_d.eqidx = [26 35 44 57 ];
M_.mapping.k_tau.eqidx = [12 26 42 ];
M_.mapping.v_tau.eqidx = [13 16 ];
M_.mapping.div.eqidx = [24 26 44 ];
M_.mapping.e_tau.eqidx = [12 16 26 36 42 60 ];
M_.mapping.nu_c.eqidx = [21 23 ];
M_.mapping.nu_g.eqidx = [22 23 ];
M_.mapping.nu_i.eqidx = [20 23 ];
M_.mapping.z.eqidx = [7 8 9 10 37 ];
M_.mapping.d.eqidx = [5 6 38 ];
M_.mapping.mu.eqidx = [11 16 39 ];
M_.mapping.wtilde.eqidx = [6 19 ];
M_.mapping.rev_c.eqidx = [40 46 ];
M_.mapping.rev_w.eqidx = [41 46 ];
M_.mapping.rev_k.eqidx = [42 46 ];
M_.mapping.rev_i.eqidx = [43 46 ];
M_.mapping.rev_d.eqidx = [44 46 ];
M_.mapping.spend_ic.eqidx = [45 46 ];
M_.mapping.rev_net.eqidx = [46 ];
M_.mapping.chat.eqidx = [47 ];
M_.mapping.ihat.eqidx = [48 ];
M_.mapping.ghat.eqidx = [49 ];
M_.mapping.pi_obs.eqidx = [50 ];
M_.mapping.r_obs.eqidx = [51 ];
M_.mapping.tau_k_hat.eqidx = [52 ];
M_.mapping.tau_l_hat.eqidx = [53 ];
M_.mapping.bhat.eqidx = [54 ];
M_.mapping.trhat.eqidx = [55 ];
M_.mapping.tau_c_hat.eqidx = [56 ];
M_.mapping.tau_d_hat.eqidx = [57 ];
M_.mapping.tau_itc_hat.eqidx = [59 ];
M_.mapping.e_tau_hat.eqidx = [60 ];
M_.mapping.tau_i_hat.eqidx = [58 ];
M_.mapping.eps_g.eqidx = [29 ];
M_.mapping.eps_tr.eqidx = [30 ];
M_.mapping.eps_k.eqidx = [27 28 ];
M_.mapping.eps_w.eqidx = [28 ];
M_.mapping.eps_z.eqidx = [37 ];
M_.mapping.eps_d.eqidx = [38 ];
M_.mapping.eps_mu.eqidx = [39 ];
M_.mapping.eps_m.eqidx = [31 ];
M_.mapping.eps_c.eqidx = [32 ];
M_.mapping.eps_ic.eqidx = [33 ];
M_.mapping.eps_ti.eqidx = [34 ];
M_.mapping.eps_td.eqidx = [35 ];
M_.mapping.eps_etau.eqidx = [36 ];
M_.mapping.eps_b.eqidx = [25 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 3 4 7 10 11 15 19 20 21 23 24 25 26 27 28 29 32 36 37 38 ];
M_.exo_names_orig_ord = [1:14];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(60, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(14, 1);
M_.params = NaN(61, 1);
M_.endo_trends = struct('deflator', cell(60, 1), 'log_deflator', cell(60, 1), 'growth_factor', cell(60, 1), 'log_growth_factor', cell(60, 1));
M_.NNZDerivatives = [286; 427; -1; ];
M_.static_tmp_nbr = [27; 17; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 0.9926375361451394;
beta = M_.params(1);
M_.params(2) = 0.025;
delta = M_.params(2);
M_.params(3) = 0.30;
theta = M_.params(3);
M_.params(4) = 5.3;
eta = M_.params(4);
M_.params(5) = 21.0;
etaw = M_.params(5);
M_.params(17) = 1.0;
pi_ss = M_.params(17);
M_.params(18) = 0.50;
h_ss = M_.params(18);
M_.params(19) = 0.2073;
g_y = M_.params(19);
M_.params(20) = 0.3220;
b_y = M_.params(20);
M_.params(16) = 0.217283;
tauw_ss = M_.params(16);
M_.params(15) = 0.419945;
tauk_ss = M_.params(15);
M_.params(60) = 0.025;
delta_tau = M_.params(60);
M_.params(40) = 0.058625;
tauc_ss = M_.params(40);
M_.params(44) = 0.017568;
tauic_ss = M_.params(44);
M_.params(56) = 0.055903;
etau_ss = M_.params(56);
M_.params(48) = 0.249417;
taui_ss = M_.params(48);
M_.params(52) = 0.299868;
taud_ss = M_.params(52);
M_.params(61) = 0.05;
divshare = M_.params(61);
M_.params(6) = 2.49;
gamma = M_.params(6);
M_.params(8) = 2.52;
sig_u = M_.params(8);
M_.params(7) = 1.99;
kappa = M_.params(7);
M_.params(9) = 48.90;
alphaP = M_.params(9);
M_.params(10) = 102.0;
alphaW = M_.params(10);
M_.params(11) = 0.96;
bc = M_.params(11);
M_.params(12) = 0.53;
thetac = M_.params(12);
M_.params(13) = 0.85;
bg = M_.params(13);
M_.params(14) = 0.98;
thetag = M_.params(14);
M_.params(21) = 0.60;
alphaR = M_.params(21);
M_.params(22) = 1.67;
alphapi = M_.params(22);
M_.params(23) = 0.09;
alphaY = M_.params(23);
M_.params(24) = 0.79;
rho_z = M_.params(24);
M_.params(25) = 0.72;
rho_d = M_.params(25);
M_.params(26) = 0.67;
rho_mu = M_.params(26);
M_.params(27) = 0.92;
rho_g = M_.params(27);
M_.params(30) = 0.64;
rho_tr = M_.params(30);
M_.params(33) = 0.91;
rho_k = M_.params(33);
M_.params(36) = 0.90;
rho_w = M_.params(36);
M_.params(39) = 0.22;
phi = M_.params(39);
M_.params(34) = 0.017;
rho_k_b = M_.params(34);
M_.params(37) = 0.020;
rho_w_b = M_.params(37);
M_.params(28) = 0.009;
rho_g_b = M_.params(28);
M_.params(31) = 0.439;
rho_tr_b = M_.params(31);
M_.params(35) = 0.148;
rho_k_y = M_.params(35);
M_.params(38) = 0.132;
rho_w_y = M_.params(38);
M_.params(29) = (-0.039);
rho_g_y = M_.params(29);
M_.params(32) = (-0.079);
rho_tr_y = M_.params(32);
M_.params(41) = 0.90;
rho_c = M_.params(41);
M_.params(42) = 0.0;
rho_c_b = M_.params(42);
M_.params(43) = 0.0;
rho_c_y = M_.params(43);
M_.params(53) = 0.90;
rho_td = M_.params(53);
M_.params(54) = 0.0;
rho_td_b = M_.params(54);
M_.params(55) = 0.0;
rho_td_y = M_.params(55);
M_.params(45) = 0.90;
rho_ic = M_.params(45);
M_.params(46) = 0.0;
rho_ic_b = M_.params(46);
M_.params(47) = 0.0;
rho_ic_y = M_.params(47);
M_.params(49) = 0.90;
rho_ti = M_.params(49);
M_.params(50) = 0.0;
rho_ti_b = M_.params(50);
M_.params(51) = 0.0;
rho_ti_y = M_.params(51);
M_.params(57) = 0.90;
rho_etau = M_.params(57);
M_.params(58) = 0.0;
rho_etau_b = M_.params(58);
M_.params(59) = 0.0;
rho_etau_y = M_.params(59);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, NaN, (-Inf), Inf, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 3, 2.0, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 3, 2.5, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 3, 2.0, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 3, 17.0, 5.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 3, 100.0, 30.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, NaN, (-Inf), Inf, 1, 0.8, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, NaN, (-Inf), Inf, 3, 1.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, NaN, (-Inf), Inf, 3, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, NaN, (-Inf), Inf, 1, 0.8, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 2, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, NaN, (-Inf), Inf, 2, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, NaN, (-Inf), Inf, 2, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, NaN, (-Inf), Inf, 2, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, NaN, (-Inf), Inf, 2, 0.15, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, NaN, (-Inf), Inf, 2, 0.15, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, NaN, (-Inf), Inf, 3, (-0.05), 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, NaN, (-Inf), Inf, 3, (-0.1), 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 39, NaN, (-Inf), Inf, 3, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 45, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 49, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 53, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 57, NaN, (-Inf), Inf, 1, 0.7, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, NaN, (-Inf), Inf, 2, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, NaN, (-Inf), Inf, 2, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 54, NaN, (-Inf), Inf, 2, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 46, NaN, (-Inf), Inf, 3, 0.0, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 58, NaN, (-Inf), Inf, 3, 0.0, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 43, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 51, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 55, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 59, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 14, NaN, (-Inf), Inf, 4, 0.05, 0.1, NaN, NaN, NaN ];
options_.bayesian_irf = true;
options_.irf = 40;
options_.lik_init = 1;
options_.load_mh_file = true;
options_.mh_drop = 0.333;
options_.mh_jscale = 0.3;
options_.mh_nblck = 2;
options_.mh_replic = 0;
options_.mode_compute = 0;
options_.nodisplay = true;
options_.prefilter = 1;
options_.datafile = 'US_Data_Matlab_1961_2013';
options_.mode_file = 'tax_dsge_est_mode';
options_.order = 1;
var_list_ = {'y';'c';'i';'h';'pi';'R';'g';'tr';'div';'taxrev';'rev_c';'rev_w';'rev_k';'rev_d';'rev_i';'spend_ic'};
oo_recursive_=dynare_estimation(var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'tax_dsge_est_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'tax_dsge_est_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'tax_dsge_est_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'tax_dsge_est_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'tax_dsge_est_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'tax_dsge_est_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'tax_dsge_est_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
